## Import Libraries

In [5]:
import pandas as pd
import random
import numpy as np
from faker import Faker
from datetime import timedelta

fake = Faker("en_IN")
random.seed(42)
np.random.seed(42)
Faker.seed(42)

## Generate Cities

In [6]:
cities = [
    ("Delhi", "Delhi"),
    ("Mumbai", "Maharashtra"),
    ("Bengaluru", "Karnataka"),
    ("Hyderabad", "Telangana"),
    ("Chennai", "Tamil Nadu"),
    ("Kolkata", "West Bengal"),
    ("Pune", "Maharashtra"),
    ("Ahmedabad", "Gujarat"),
    ("Jaipur", "Rajasthan"),
    ("Lucknow", "Uttar Pradesh"),
    ("Chandigarh", "Chandigarh"),
    ("Indore", "Madhya Pradesh"),
    ("Bhopal", "Madhya Pradesh"),
    ("Surat", "Gujarat"),
    ("Nagpur", "Maharashtra")
]

cities_df = pd.DataFrame(
    cities,
    columns=["city_name", "state"]
)

cities_df.insert(0, "city_id", range(1, len(cities_df)+1))

cities_df.head()

   city_id  city_name        state
0        1      Delhi        Delhi
1        2     Mumbai  Maharashtra
2        3  Bengaluru    Karnataka
3        4  Hyderabad    Telangana
4        5    Chennai   Tamil Nadu

## saving it

In [7]:
cities_df.to_csv("../data/cities.csv", index=False)

print("Cities CSV Saved Successfully!")

Cities CSV Saved Successfully!

## Generate Customers

In [8]:
customers = []

for i in range(1,1001):

    gender = random.choice(["Male","Female"])

    if gender=="Male":
        first = fake.first_name_male()
    else:
        first = fake.first_name_female()

    last = fake.last_name()

    customers.append([

        i,
        first,
        last,
        gender,
        random.randint(18,60),
        fake.unique.phone_number()[:10],
        fake.unique.email(),
        random.randint(1,15),
        fake.date_between("-4y","today")

    ])

customers_df = pd.DataFrame(customers,columns=[

"customer_id",
"first_name",
"last_name",
"gender",
"age",
"phone",
"email",
"city_id",
"join_date"

])

customers_df.head()

,customer_id,first_name,last_name,gender,age,phone,email,city_id,join_date
0,1,Daksh,Bakshi,Male,19,4332181960,chandertejas@example.org,12,2024-09-21
1,2,Amara,Issac,Female,33,8637940265,nachiket35@example.org,4,2022-12-20
2,3,Ranveer,Chatterjee,Male,24,0594078161,janaki93@example.net,11,2022-11-14
3,4,Arin,Kari,Male,55,0131647525,amarabora@example.net,7,2025-04-10
4,5,Frederick,Walla,Male,19,3276483503,muttinandini@example.com,2,2022-11-08

In [10]:
customers_df.to_csv("../data/customers.csv",index=False)

## Restaurants

In [11]:
restaurant_names = [

"Burger Hub",
"Pizza Point",
"Biryani House",
"Tandoori Flames",
"Punjabi Tadka",
"Chinese Express",
"Spice Villa",
"Food Junction",
"South Treat",
"Royal Kitchen"

]

cuisines = [

"North Indian",
"South Indian",
"Chinese",
"Italian",
"Mughlai",
"Fast Food",
"Desserts"

]

restaurants=[]

for i in range(1,151):

    restaurants.append([

        i,
        random.choice(restaurant_names)+" "+str(i),
        random.choice(cuisines),
        random.randint(1,15),
        round(random.uniform(3.5,5.0),1),
        random.randint(2008,2024)

    ])

restaurants_df=pd.DataFrame(restaurants,columns=[

"restaurant_id",
"restaurant_name",
"cuisine",
"city_id",
"rating",
"opening_year"

])

restaurants_df.to_csv("../data/restaurants.csv",index=False)

## Delivery partners

In [12]:
partners=[]

vehicles=["Bike","Scooter","Cycle"]

for i in range(1,251):

    partners.append([

        i,
        fake.name(),
        random.choice(vehicles),
        random.randint(1,10),
        round(random.uniform(3.5,5.0),1)

    ])

partners_df=pd.DataFrame(partners,columns=[

"partner_id",
"partner_name",
"vehicle_type",
"experience_years",
"rating"

])

partners_df.to_csv("../data/delivery_partners.csv",index=False)

## orders

In [13]:
statuses=["Delivered","Cancelled","Preparing"]

orders=[]

for i in range(1,10001):

    orders.append([

        i,
        random.randint(1,1000),
        random.randint(1,150),
        random.randint(1,250),
        fake.date_time_between("-2y","now"),
        random.randint(15,70),
        random.choices(

            statuses,

            weights=[85,5,10]

        )[0],
        round(random.uniform(150,1800),2)

    ])

orders_df=pd.DataFrame(orders,columns=[

"order_id",
"customer_id",
"restaurant_id",
"partner_id",
"order_date",
"delivery_time_minutes",
"order_status",
"total_amount"

])

orders_df.to_csv("../data/orders.csv",index=False)

## order items

In [14]:
foods = [
    ("Veg Burger","Fast Food"),
    ("Chicken Burger","Fast Food"),
    ("Paneer Pizza","Italian"),
    ("Chicken Pizza","Italian"),
    ("Veg Biryani","North Indian"),
    ("Chicken Biryani","North Indian"),
    ("Masala Dosa","South Indian"),
    ("Idli","South Indian"),
    ("Noodles","Chinese"),
    ("Fried Rice","Chinese"),
    ("Ice Cream","Desserts"),
    ("Brownie","Desserts")
]

items=[]

item_id=1

for order in range(1,10001):

    no_items=random.randint(1,4)

    for _ in range(no_items):

        food=random.choice(foods)

        items.append([

            item_id,
            order,
            food[0],
            food[1],
            random.randint(1,3),
            round(random.uniform(80,450),2)

        ])

        item_id+=1

items_df=pd.DataFrame(items,columns=[

"item_id",
"order_id",
"food_name",
"category",
"quantity",
"unit_price"

])

items_df.to_csv("../data/order_items.csv",index=False)

## payments

In [15]:
payments=[]

methods=["UPI","Card","Cash","Wallet"]

for i in range(1,10001):

    payments.append([

        i,
        i,
        random.choice(methods),
        random.choices(

            ["Success","Failed"],

            weights=[95,5]

        )[0]

    ])

payments_df=pd.DataFrame(payments,columns=[

"payment_id",
"order_id",
"payment_method",
"payment_status"

])

payments_df.to_csv("../data/payments.csv",index=False)

## reviews

In [16]:
feedbacks=[
    "Excellent food",
    "Very tasty",
    "Fast delivery",
    "Late delivery",
    "Packaging could improve",
    "Highly recommended",
    "Average experience",
    "Loved it",
    "Will order again",
    "Food was cold"
]

reviews=[]

for i in range(1,10001):

    reviews.append([

        i,
        i,
        random.randint(1,5),
        random.choice(feedbacks)

    ])

reviews_df=pd.DataFrame(reviews,columns=[

"review_id",
"order_id",
"customer_rating",
"feedback"

])

reviews_df.to_csv("../data/reviews.csv",index=False)

In [14]:
import os

print(os.getcwd())

C:\Windows\System32

In [1]:
import os

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
C:\Users\Sneha\OneDrive\Documents\Desktop\Food-Delivery-Analytics\notebooks

In [2]:
import os

os.makedirs("../data", exist_ok=True)

print("Folder Created Successfully!")

Folder Created Successfully!

In [3]:
import os

print(os.listdir(".."))

['data', 'notebooks', 'screenshots', 'sql', 'visuals']

In [17]:
import os

print(os.listdir("../data"))

['cities.csv', 'customers.csv', 'delivery_partners.csv', 'orders.csv', 'order_items.csv', 'payments.csv', 'restaurants.csv', 'reviews.csv']

In [1]:
!pip install mysql-connector-python sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.4-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Python312\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-26.7.0-py2.py3-none-any.whl (480 kB)
Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 5.5 MB/s  0:00:00
Downloading greenlet-3.5.4-cp312-cp312-win_amd64.whl (247 kB)
Installing collected packages: mysql-connector-python, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.4 mysql-connector-python-26.7.0 sqlalchemy-2.0.51

WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

print("Orders:", pd.read_csv("../data/orders.csv").shape)
print("Order Items:", pd.read_csv("../data/order_items.csv").shape)
print("Payments:", pd.read_csv("../data/payments.csv").shape)
print("Reviews:", pd.read_csv("../data/reviews.csv").shape)

Orders: (10000, 8)
Order Items: (24708, 6)
Payments: (10000, 4)
Reviews: (10000, 4)